belav/csharpier

- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.actual.cst
- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
- Src/CSharpier/PrinterHelpers/BaseTypeDeclarationSyntax.cs
This is really more of a bug report than anything else - I just figured I could write a unit test for the same amount of effort it takes would have taken to describe it in an issue. :smile:
> Add test case for record declarations without body

- Src/CSharpier.Tests/TestFiles/ForEachStatement/BasicForEachStatement.cst
- Src/CSharpier/Printer/CompilationUnitSyntax.cs
- Src/CSharpier/Printer/ForEachStatementSyntax.cs
- Src/CSharpier/PrinterHelpers/SyntaxTrivia.cs
- Src/CSharpier/SyntaxPrinter/SyntaxTokens.cs
> Clean up foreach code, create new SyntaxTokens Print class

- Src/CSharpier.Tests/TestFiles/ConditionalExpression/BasicConditionalExpression.cst
- Src/CSharpier.Tests/TestFiles/ConditionalExpression/ConditionalExpressions.cst
- Src/CSharpier.Tests/TestFiles/ConditionalExpression/_ConditionalExpressionTests.cs
- Src/CSharpier/Printer/ConditionalExpressionSyntax.cs
> conditional expression formatting

- Src/CSharpier.Tests/TestFiles/IsPatternExpression/IsPatternExpressions.cst
- Src/CSharpier.Tests/TestFiles/IsPatternExpression/_IsPatternExpressionTests.cs
- Src/CSharpier/Printer/BinaryPatternSyntax.cs
- Src/CSharpier/Printer/IsPatternExpressionSyntax.cs
> break is pattern

- Src/CSharpier.Tests/TestFiles/BinaryExpression/StringConcatenation.cst
- Src/CSharpier/Printer/BinaryExpressionSyntax.cs
> don't break string concatenation for now

- Src/CSharpier.Tests/TestFiles/ForEachStatement/ForEachStatements.cst
- Src/CSharpier.Tests/TestFiles/UsingStatement/UsingStatements.cst
- Src/CSharpier/Printer/ForEachStatementSyntax.cs
- Src/CSharpier/Printer/UsingStatementSyntax.cs
- Src/CSharpier/SyntaxPrinter/SyntaxTokens.cs
> fixing some space brace related issues

- Src/CSharpier.Tests/TestFiles/BinaryExpression/StringConcatenation.cst
- Src/CSharpier.Tests/TestFiles/ElseStatement/ElseStatements.cst
- Src/CSharpier.Tests/TestFiles/FieldDeclaration/BasicField.cst
- Src/CSharpier.Tests/TestFiles/ForStatement/ForStatements.cst
- Src/CSharpier.Tests/TestFiles/IfStatement/IfStatements.cst
- Src/CSharpier.Tests/TestFiles/InterpolatedStringExpression/InterpolatedStringExpressions.cst
- Src/CSharpier.Tests/TestFiles/QueryExpression/QueryExpressions.cst
- Src/CSharpier.Tests/TestFiles/ReturnStatement/ReturnStatements.cst
- Src/CSharpier.Tests/TestFiles/WhileStatement/WhileStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BinaryExpression.cs
> breaking before binary operator

- Src/CSharpier.Tests/TestFiles/IsPatternExpression/IsPatternExpressions.cst
- Src/CSharpier/Printer/IsPatternExpressionSyntax.cs
> Breaking IsPattern better

- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/TestFiles/ReturnStatement/ReturnStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ReturnStatement.cs
> Indent binary returns

- .csharpierrc
- Src/CSharpier.Tests/SyntaxNodeComparerTests.cs
- Src/CSharpier.Tests/TestFiles/AttributeList/AttributeLists.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Parameter.cs
switching to crlf
closes #104
closes #174
> Adding Line after attribute on parameter

- .csharpierrc
- Src/CSharpier.Tests/CodeFormatterTests.cs
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/TestFiles/BaseTest.cs
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/ConfigurationFileOptions.cs
- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/PrinterOptions.cs
- Src/CSharpier/Program.cs
> Implementing auto line ending

- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
> fixing extra line bug with complex initializer

- Src/CSharpier.Tests/TestFiles/PropertyDeclaration/PropertyDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BasePropertyDeclaration.cs
> properties with modifiers shouldn't break unless they hit width

- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
> Fixing generic records

- CSharpier.sln.DotSettings
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
- Src/CSharpier.Tests/LineEndingTests.cs
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/ConfigurationFileOptions.cs
- Src/CSharpier/IConsole.cs
- Src/CSharpier/IgnoreFile.cs
- Src/CSharpier/Program.cs
> Support looking for config and ignore files in parent directories

- Src/CSharpier.Tests/TestFiles/Directives/Directives.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CompilationUnit.cs
> Fixing bug with end of file trivia inserting extra lines in some cases

- Src/CSharpier.Tests/ResultPrinterTests.cs
- Src/CSharpier.Tests/Utilities/StringDifferTests.cs
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/ResultPrinter.cs
- Src/CSharpier/Utilities/StringDiffer.cs
> adding ability to display differences when --check fails

- Src/CSharpier.Tests/TestFiles/FieldDeclaration/FieldDeclarations.cst
- Src/CSharpier.Tests/TestFiles/VariableDeclaration/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/VariableDeclaration.cs
> Fix indentation of lambdas during declaration

- Src/CSharpier.Tests/TestFiles/ObjectCreationExpression/ObjectCreationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ArgumentList.cs
> Fix breaking in constructors when creating object

- .github/workflows/validatePR.yml
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/Utilities/StringDifferTests.cs
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/IConsole.cs
- Src/CSharpier/Program.cs
Also added a github action to test the stdin functionality.
> cleaner reading of stdin, use encoding from stdin

- Src/CSharpier.Tests/TestFiles/ForEachStatement/ForEachStatements.cst
- Src/CSharpier.Tests/TestFiles/ForStatement/ForStatements.cst
- Src/CSharpier.Tests/TestFiles/IfStatement/IfStatements.cst
- Src/CSharpier.Tests/TestFiles/WhileStatement/WhileStatements.cst
- Src/CSharpier/SyntaxPrinter/OptionalBraces.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ElseClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForEachStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IfStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/WhileStatement.cs
We haven't heard any compelling arguments for not always breaking. And from looking at public repos it appears that always breaking is more common.
closes #303
closes #245
closes #255
> Always break + indent with optional braces

- Src/CSharpier.Playground/Startup.cs
- Src/CSharpier.Tests/TestFiles/ImplicitArrayCreationExpression/ImplicitArrayCreationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ImplicitArrayCreationExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
> Format Implicit Array Initializer consistently

- Src/CSharpier.Tests/TestFiles/VariableDeclaration/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ArrayRankSpecifier.cs
> Fixing bug with empty array ranks breaking

- Src/CSharpier.Tests/TestFiles/TryStatement/TryStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CatchClause.cs
> Improved logic for where to break long catch clauses

- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
These test cases were resolved as part of #275. The final case isn't what we want, but #298 will address it when it is closed.
> Adding test cases for records

- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
> Format record braces consistently with class

- Src/CSharpier.Tests/TestFiles/DoStatement/DoStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/DoStatement.cs
This change mimics the `while` statement.
Updates #37
> Better format condition of do-while

- Src/CSharpier.Tests/TestFiles/IsPatternExpression/IsPatternExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IsPatternExpression.cs
> Better format "is" operator

- Src/CSharpier.Tests/TestFiles/ParenthesizedExpression/ParenthesizedExpressions.cst
- Src/CSharpier.Tests/TestFiles/ParenthesizedExpression/_ParenthesizedExpressionTests.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ParenthesizedExpression.cs
> Put parenthesized expressions onto a newline and indent them

- Src/CSharpier.Tests/TestFiles/ForStatement/ForStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForStatement.cs
> Improving ForStatement edge cases

- Src/CSharpier.Tests/TestFiles/MethodDeclaration/MethodDeclarations.cst
- Src/CSharpier.Tests/TestFiles/SwitchStatement/SwitchStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Block.cs
> Ensure block in block doesn't get extra Line

- Src/CSharpier.Tests/TestFiles/ArrayCreationExpression/ArrayCreationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ArrayRankSpecifier.cs
> Making sure array ranks will break

- Src/CSharpier.Tests/TestFiles/ConditionalExpression/ConditionalExpressions.cst
- Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ConditionalExpression.cs
> Don't indent conditionals too much

- Src/CSharpier.Tests/TestFiles/SwitchStatement/SwitchStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IfStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchStatement.cs
> SwitchStatement now space braces

- Src/CSharpier.Tests/TestFiles/DoStatement/DoStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/DoStatement.cs
> Better do while formatting

- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ImplicitObjectCreationExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
> Fixing issue with implicit object creation breaking weird

- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/DocPrinter/DocFitter.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Directives should not affect if code breaks

- Src/CSharpier.Tests/TestFiles/AttributeList/AttributeLists.cst
- Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst
- Src/CSharpier/SyntaxPrinter/AttributeLists.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TypeParameter.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TypeParameterList.cs
> Cleaning up breaking of attributes on generic type parameters

- Src/CSharpier.Tests/TestFiles/BinaryExpression/BinaryExpressions.cst
- Src/CSharpier.Tests/TestFiles/FieldDeclaration/FieldDeclarations.cst
- Src/CSharpier.Tests/TestFiles/ForStatement/ForStatements.cst
- Src/CSharpier.Tests/TestFiles/IfStatement/IfStatements.cst
- Src/CSharpier.Tests/TestFiles/ParenthesizedLambdaExpression/ParenthesizedLambdaExpressions.cst
- Src/CSharpier.Tests/TestFiles/SwitchExpression/SwitchExpressions.cst
- Src/CSharpier.Tests/TestFiles/VariableDeclaration/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BinaryExpression.cs
This is the initial work for getting BinaryExpressions formatting better.
A few of edge cases were split off into different tickets. #355 #356 #357
closes #37
> Better formatting for binary expressions

- Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/TestFiles/PropertyDeclaration/PropertyDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TypeArgumentList.cs
> Cleaning up formatting for nested TypeArguments

- Src/CSharpier.Tests/TestFiles/SwitchExpression/SwitchExpressions.cst
- Src/CSharpier.Tests/TestFiles/SwitchStatement/SwitchStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CasePatternSwitchLabel.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/WhenClause.cs
> Prefer breaking before `when` clause, instead of inside

- Src/CSharpier.Tests/TestFiles/LockStatement/LockStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/LockStatement.cs
> make sure to print new lines before lock statements

- Src/CSharpier.Tests/TestFiles/SwitchExpression/SwitchExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
> Fixing extra line break issue + better formatting for an edge case

- Src/CSharpier.Tests/DisabledTextComparerTests.cs
- Src/CSharpier/DisabledTextComparer.cs
> Fixing trailing whitespace edgecase

- Src/CSharpier.Tests/FormattingTests/TestFiles/ConditionalExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BinaryExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ConditionalExpression.cs
> Improving formatting of conditional in argument list

- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/ConfigurationFileOptions.cs
> Don't blow up on empty config file

- Scripts/CreateTestingPR.ps1
- Src/CSharpier.Tests/FormattingTests/TestFiles/FixedStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/FixedStatement.cs
> Fixing nested fixed statements

- CSharpier.sln
- Docs/IntegratingWithLinters.md
- README.md
- Src/CSharpier.Benchmarks/Program.cs
- Src/CSharpier.Generators/SyntaxNodeComparerGenerator.cs
- Src/CSharpier.Generators/SyntaxNodeJsonWriterGenerator.cs
- Src/CSharpier.Playground/Controllers/FormatController.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
- Src/CSharpier.Tests/DeepRecursionTests.cs
- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/MissingTypeChecker.cs
- Src/CSharpier.Tests/Samples/Samples.cs
- Src/CSharpier.Tests/SyntaxNodeComparerTests.cs
- Src/CSharpier.Tests/SyntaxPrinter/PreprocessorSymbolsTests.cs
- Src/CSharpier.Tests/Utilities/StringDifferTests.cs
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/ConsoleLogger.cs
- Src/CSharpier/DocPrinter/Indent.cs
- Src/CSharpier/IgnoreFile.cs
- Src/CSharpier/SyntaxNodeComparer.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BasePropertyDeclaration.cs
- Src/CSharpier/Utilities/StringBuilderExtensions.cs
Also ran dotnet format without formatting rules
> Adding doc on integrating with dotnet format

- Src/CSharpier.Tests/FormattingTests/TestFiles/AssignmentExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AssignmentExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/VariableDeclaration.cs
> Improving formatting of chained assignments

- Src/CSharpier.Tests/FormattingTests/TestFiles/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ImplicitObjectCreationExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ObjectCreationExpression.cs
> Break nested initializers

- Src/CSharpier.Tests/FormattingTests/TestFiles/GlobalStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/GlobalStatement.cs
> Fixing extra newlines in global statements

- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/JoinClause.cs
> Fix join losing code

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
> Ensure we print nice bad path message

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/HasMismatchedCliAndMsBuildVersions.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
> Detect mismatch between cli and msbuild versions

- Src/CSharpier.Tests/FormattingTests/TestFiles/Comments.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Include new line before comments that end a block

- Src/CSharpier.Tests/FormattingTests/TestFiles/ForStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForStatement.cs
> Cleaning up formatting of fors with empty statements

- Src/CSharpier.Tests/FormattingTests/TestFiles/CompilationUnitIfDirectiveEdgeCase6.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CompilationUnitIfDirectiveEdgeCase7.cst
- Src/CSharpier/SyntaxPrinter/NamespaceLikePrinter.cs
> More edgecases in compilation unit

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
I believe this is a better way of dealing with the threads that read the output from the long running csharpier process.
closes #568
> Better way of dealing of threads 

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessPipeMultipleFiles.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Remove threads, reading from stderror isn't reliable and the method of reading with threads left threads hanging.

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
> Adding support for 2022.1

- Src/CSharpier.Tests/FormattingTests/TestFiles/CastExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CastExpression.cs
> Improve formatting for casting

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
> Error output loses characters, so let's just ditch it.

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/HasMismatchedCliAndMsBuildVersions.cs
> Fixing bug with empty csproj causing csharpier to fail

- Src/CSharpier.FakeGenerators/Ignored.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/StringLiterals.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InterpolatedStringExpression.cs
> Interpolated verbatim comment

- Src/CSharpier.Tests/FormattingTests/TestFiles/PropertyDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
> Fixing extra space in property initializer

- Src/CSharpier.Cli/IgnoreFile.cs
Add the ability to easily add more default ignores if wanted. As requested by #699
> Add node_modules as a default ignore

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Adding support for reading version of csharpier.msbuild from csproj

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/CONTRIBUTING.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessProvider.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ReformatWithCSharpierAction.java
> Code changes for reading msbuild version in rider plugin

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package-lock.json
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcess.ts
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/CustomPathInstaller.ts
> Detect and recover from bad custom path install

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CustomPathInstaller.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> detect and fix bad csharpier install

- Scripts/UpdateCSharpierRepos.ps1
- Src/CSharpier.Tests/FormattingTests/TestFiles/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/PropertyDeclarations.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/TupleExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TupleType.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TypeArgumentList.cs
> Cleaning up how tuples format in more complex situations

- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AnonymousObjectCreationExpression.cs
> Break anonymous object creation the same as object initializer

- .gitignore
- Src/CSharpier.Generators/NodePrinterGenerator.sbntxt
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.expected.cst
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
- Src/CSharpier/SyntaxPrinter/FormattingContext.cs
- Src/CSharpier/SyntaxPrinter/MembersWithForcedLines.cs
- Src/SyntaxFinder/SyntaxFinder.csproj
> Fix so that empty lines inside of ranged ignores are maintained.

- Src/CSharpier.Tests/FormattingTests/TestFiles/ClassDeclarations.cst
- Src/CSharpier/CSharpier.csproj
> File scoped types

- Src/CSharpier.Tests/FormattingTests/TestFiles/ClassDeclarations.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/ClassDeclarations_Tabs.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/DelegateDeclarations.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/TypeParameterConstraintClauses.cst
- Src/CSharpier/SyntaxPrinter/ConstraintClauses.cs
> Put generic constraints on new line

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package-lock.json
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/CustomPathInstaller.ts
> Fix for multiple instances of vscode not working

- Src/CSharpier.VSCode/README.md
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/Extension.ts
- Src/CSharpier.VSCode/src/InstallerService.ts
> Detect extension running remotely and provide better install message

- Src/CSharpier.Tests/FormattingTests/TestFiles/Directives.cst
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/DocPrinter/DocFitter.cs
- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/DocSerializer.cs
- Src/CSharpier/DocTypes/AlwaysFits.cs
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Fixing weird edge case with #if directives

- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ReturnStatement.cs
> Fix for return query expression not indenting

- Src/CSharpier.Tests/FormattingTests/TestFiles/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Fixing weird edge that involved initializers + invocations on them.

- Src/CSharpier.Tests/FormattingTests/TestFiles/ImplicitArrayCreationExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
> Always break dictionary and array initializers in some cases.

- Src/CSharpier.Tests/FormattingTests/TestFiles/TypeArgumentLists.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TypeArgumentList.cs
> Fixing edge case for open generics

- Docs/Ignore.md
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.expected.cst
- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
- Src/CSharpier/SyntaxPrinter/MembersWithForcedLines.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Allow descriptions in csharpier ignore comments

- Src/CSharpier.VisualStudio/CONTRIBUTING.md
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/CSharpier.VisualStudio.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/CSharpier.VisualStudio2019.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/InfoBarService.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/InstallerService.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpierOnSave.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Ignore a couple of "csharpier must be installed globally" messages

- Src/CSharpier.FakeGenerators/SyntaxNodeComparerGenerator.cs
- Src/CSharpier.FakeGenerators/SyntaxNodeJsonWriterGenerator.cs
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/SyntaxNodeComparer.generated.cs
- Src/CSharpier/SyntaxNodeJsonWriter.cs
- Src/CSharpier/SyntaxNodeJsonWriter.generated.cs
- Src/CSharpier/SyntaxPrinter/UnhandledNode.cs
> better handling of unsupported syntax node types

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Tests/Utilities/StringDifferTests.cs
- Src/CSharpier/Utilities/StringDiffer.cs
> Better error for missing or extra EOF newline

- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.expected.cst
- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
> Fixing issue of inserting extra new lines into csharpier ignores

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UnhandledNode.test
- Src/CSharpier/SyntaxPrinter/UnhandledNode.cs
> Print leading trivia on unhandled nodes

- Src/CSharpier.Tests/CSharpierIgnoreTests.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.test
- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
> Fixing regression on csharpier ignore that was deleting empty lines

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/resources/META-INF/plugin.xml
> Optimize rider settings window

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/CSharpier.VisualStudio.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/CSharpier.VisualStudio2019.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpierOnSave.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Potential fix for format on save not working in latest VS

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/IfStatements.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BinaryExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IfStatement.cs
> Avoid breaking only around binary expression but not binary expression itself

- .github/workflows/publish_nuget.yml
- .github/workflows/validate_pull_request.yml
- Directory.Packages.props
- Src/CSharpier.Cli.Tests/CSharpier.Cli.Tests.csproj
- Src/CSharpier.Tests/CSharpier.Tests.csproj
This adds the [GitHubActionsTestLogger](https://github.com/Tyrrrz/GitHubActionsTestLogger) package to preview test results on GitHub.
> Show test results on GitHub

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/StringLiterals.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InterpolatedStringExpression.cs
> Fix issue with eating comments on raw literals with c# that has new lines

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/README.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ReformatWithCSharpierOnSave.java
> Only wait 3 seconds for csharpier to format, otherwise kill it and restart it.

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ReformatWithCSharpierOnSave.java
- Src/CSharpier.Rider/src/main/resources/META-INF/plugin.xml
> Fix for the rider plugin hanging. When the error stream filled up without being read it couldn't read from the input stream was waiting indefinitely

- .config/dotnet-tools.json
- Directory.Build.props
- Shell/BuildProject.psm1
- Shell/ReviewBranch.psm1
- Src/CSharpier.Cli/CSharpier.Cli.csproj
- Src/CSharpier.Generators/CSharpier.Generators.csproj
- Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
- Src/CSharpier/CSharpier.csproj
- global.json
> Support for net8

- Src/CSharpier.Playground/Properties/launchSettings.json
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
> Fixing some issues with collection expressions

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
> Fixing bug with no longer finding config files for piped in files

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ExpressionElement.cs
> Fixing a number of bugs with collection expressions

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> indent comments on close bracket.

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/FormattingService.java
> Ensure that the plugin always uses \n.

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
> Also format csx files

- .idea/.idea.CSharpier/.idea/CSharpierPlugin.xml
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
> Fix empty line before collection expression in attribute

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsStaticSystemToTop.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsStaticSystemToTop.test
- Src/CSharpier/SyntaxPrinter/UsingDirectives.cs
> Sort static system usings above other static usings

- Src/CSharpier.Cli/Program.cs
> Fixed an exception in projects with editorconfig

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchStatements.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchSection.cs
> Fixing extra new line inside case

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/README.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessProvider.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessServer.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessSingleFile.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierSettings.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierSettingsComponent.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/DotNetProvider.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/FormattingService.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ICSharpierProcess.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/NullCSharpierProcess.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ReformatWithCSharpierAction.java
Added support for using CSharpier http server on 0.28.0+ #1191 #1109
Fixed deprecated warning #1224
Added the csharpier version to the information logged when a file is formatted
> Rider changes needed to support #1191 & #1109

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessServer.java
> Fix encoding issue with unicode + csharpier 0.28+

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/Options/ConfigurationFileOptions.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
> Limit config searching the same way editorconfig searching is limited

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/InterpolatedStringExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InterpolatedStringExpression.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Pull trailing trivia out of forced flat portion of interpolated string

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchExpressions.test
- Src/CSharpier/SyntaxPrinter/FormattingContext.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchExpression.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Handle more comments on switch arms

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
> Fixing repeated new line being added within switch expressions

- Src/CSharpier.Cli/Server/ServerFormatter.cs
See [this](https://github.com/belav/csharpier/issues/1249#issuecomment-2129993017) for why there are problems with trying to find a free port on our own. Letting kestrel pick the port seems like a much better option.
references #1249
> Let kestrel pick the open port

- Src/Website/docs/IntegratingWithLinters.md
- docs/IntegratingWithLinters.md
> Add SA1515 to the list to de disabled

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/IndexerDeclarations.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BracketedParameterList.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ParameterList.cs
> Make sure indexer declarations print consistently with other parameter lists

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ConditionalExpressions.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ConditionalExpressions_Tabs.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ObnoxiousEdgeCases.test
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ConditionalExpression.cs
> Don't indent chained ternarys, format them more like switch expressions.

- Src/CSharpier.VisualStudio/.idea/.idea.CSharpier.VisualStudio/.idea/CSharpierPlugin.xml
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpier.VisualStudioShared.projitems
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/FunctionRunner.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> VS - Use dotnet tool list to find both local and global installs of csharpier.

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_UnderscoreSort.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_UnderscoreSort.test
- Src/CSharpier/SyntaxPrinter/UsingDirectives.cs
> Getting _ to sort to the top like it should

- Src/CSharpier.Cli/EditorConfig/EditorConfigSections.cs
- Src/CSharpier.Cli/EditorConfig/Section.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
- docs/Configuration.md
> Support custom file extensions with editor config

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/TrailingComma_TrailingComments.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/TrailingComma_TrailingComments.test
- Src/CSharpier/SyntaxPrinter/FormattingContext.cs
- Src/CSharpier/SyntaxPrinter/SeparatedSyntaxList.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
- Src/CSharpier/SyntaxPrinter/TrailingComma.cs
> Fixing issue with a trailing comma being added after a trailing comment

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
> Fixing extra line + indent with collection expression on fields

- docs/Editors.md
Added info on Neovim to use Conform.
> Update Editors.md with conform.nvim suggestion for Neovim

- Src/CSharpier.Cli/CSharpier.Cli.csproj
> revert tool command, this was supposed to be in 1.0.0 only

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
> fixing another extra line issue

- Shell/PublishVS.psm1
- Src/CSharpier.VisualStudio/CONTRIBUTING.md
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/CSharpier.VisualStudio.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/CSharpier.VisualStudio2019.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierOptions.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Fixing bug for VS2022 options page not working when no solution open.

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/CSharpier.VisualStudio.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/CSharpier.VisualStudio2019.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/ChangeLog.md
> Fixing issue with older versions of VS not working

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/Comments_EndOfFileManyLines.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/Comments_EndOfFileManyLines.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CompilationUnit.cs
> Improving the hack that ensures we don't keep adding new lines before a file ending comment

- Src/Website/docs/Configuration.md
- docs/Configuration.md
> Updating doc to use the standard glob pattern for matching multiple extensions

- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/FormattingService.java
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/CSharpier.VisualStudio.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/CSharpier.VisualStudio2019.csproj
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpier.VisualStudioShared.projitems
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierOptions.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierPackage.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessPipeMultipleFiles.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessServer.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CustomPathInstaller.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/FormattingService.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ICSharpierProcess.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpier.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpierOnSave.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/Semver.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Getting visual studio plugin working with csharpier 1.0.0

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessServer.java
- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/CSharpierProcessServer.ts
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessServer.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
Fixes #1468 by changing the process working directory of the `--server` process to the csharpier cache directory.
> Rider: Set server pwd to cache dir

- Src/CSharpier.Cli/Server/ServerFormatter.cs
Fixes #1468 (`dotnet-csharpier --server` accidentally installs file system watches for the entire directory.)
We configure the server to run against a temporary, empty directory instead, so that the file system watcher that does get installed only has to watch a single, empty directory.
This also means that the server won't pick up the default appsettings.json files in the working directory. We probably don't want this anyway because these appsettings could be intended for the user's solution, not for csharpier.
Alternative approaches are discussed in #1468
> Avoid excessive file system watches for --server

- Src/Website/src/pages/index.js
> Update website to call out c# 13 support

- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchExpression.cs
Conditionally create group id strings when they are not always needed. Saves 2MB
> feat: conditionally create group id

- Src/CSharpier/DocPrinter/Indent.cs
Add cache to `IncreaseIndent`and use `PadRight`. Saves 4MB 6% of memory.
- Could this be a `List<Indent>`? If I understand correctly csharpier won't change between tabs and space mode, so this should be okay right?
- Assumes that `TypesForTabs` is only used for tabs mode.
- `AddAlign` and `MakeIndentWithTypesForTabs` could be improved, I should run the benchmarks with tabs mode enabled to see if its worth it.
| Default_CodeFormatter | 234.9 ms | 11.21 ms | 33.05 ms | 7000.0000 | 3000.0000 | 1000.0000 |  66.17 MB |
| Default_CodeFormatter | 223.6 ms | 9.96 ms | 29.36 ms | 212.7 ms | 7000.0000 | 3000.0000 | 1000.0000 |  62.18 MB |
> feat: cache `Indent` and use `PadRight`

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ParenthesizedLambdaExpressions.test
- Src/CSharpier/SyntaxPrinter/ArgumentListLikeSyntax.cs
> Getting lambda formatting consistent

- Src/CSharpier/SyntaxPrinter/SeparatedSyntaxList.cs
Add `ValueListBuilder` to `SeparatedSyntaxList` saving 0.9 MB.
I compared the length of the input `SeparatedSyntaxList` and returned `doc` `List<Doc>`, (lengths are left and right respectively). 70% of all output lists are under 8 values, so I chose a default capacity of 8 for the scratch buffer.
`SeparatedSyntaxList.Print` will add at most 3 items to the output list per item in `SeparatedSyntaxList<T> list`, knowing this I decided that `ValueListBuilder` should rent an array from the `ArrayPool` that can contain all the values. This way we don't have to bother with the overhead of resizing.
| Method                | Mean     | Error   | StdDev  | Gen0      | Gen1      | Gen2     | Allocated |
|---------------------- |---------:|--------:|--------:|----------:|----------:|---------:|------ …
> perf: use `ValueListBuilder` for `SeparatedSyntaxList`

- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
> feat: use source generated regex

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/AttributeLists.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Parameter.cs
> Finding a fix for parameter being indented when the attribute on said parameter has a comment

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ExpressionStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Fixing issue with commenting out final invocation in fluent call which led to collapsed invocation

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/AttributeLists.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/PropertyDeclarations.test
- Src/CSharpier/SyntaxPrinter/AttributeLists.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BasePropertyDeclaration.cs
> Don't always break attributes on property accessors

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/GenericName.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> fixing issue with comment on generic causing member chain to break

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/GlobalStatements.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Block.cs
> Fix for extra line added to block when it is a global statement

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/InterpolatedStringExpressions.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/RawStringLiterals.test
- Add test to catch `{{` formatting errors in interpolated raw strings
- Add test for extended length raw string quotes `"""""`
Resolves #1494
> test: add raw interpolated string test and add multi "" test to raw string literal

- Shell/ReviewBranch.psm1
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ParenthesizedExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IsPatternExpression.cs
> Fixing inconsistent indentation with parenthisized expression

- .github/workflows/publish_nuget.yml
just noticed this while browsing around :D
> fix: Release Core project

- CHANGELOG.md
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- docs/Ignore.md
Will hopefully be re-enabled with #1587
closes #1584
> The support for gitignore kills performance and there isn't a straightforward fix

- Src/CSharpier.Cli/FormattingCommands.cs
> Update help text to not be c# specific

- Src/CSharpier.Core/CSharp/SyntaxPrinter/SyntaxNodePrinters/WhenClause.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchExpressions.test
> Keep discard with when on long arms

- .github/workflows/ValidatePullRequest.yml
- .github/workflows/ValidatePullRequest_CheckTodos.ps1
- Src/CSharpier.Core/PrinterOptions.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
- docs/Configuration.md
- docs/Pre-commit.md
> Support formatting of xaml and slnx files by default

- Directory.Packages.props
- Src/CSharpier.Core/CSharp/CSharpFormatter.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/DotnetRun.test
> Updating roslyn and making sure csharpier can parse file based programs.

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/CommandLineOptions.cs
- Src/CSharpier.Cli/FormattingCommands.cs
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Core/PrinterOptions.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- docs/CLI.md
> Supporting stdin-filepath, dealing with gitignore when there is no path specified and handling non-c# files when no path is specified

- Src/CSharpier.Core/CSharp/SyntaxPrinter/SeparatedSyntaxList.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.test
> Fixing issue with ignore range and trailing comma
