- Src/Worker/GeneratePrinterSwitch.cs
- Src/Worker/SyntaxNodeComparerGenerator.cs
- Src/Worker/SyntaxNodeJsonWriterGenerator.cs
- Src/Worker/TypescriptNodeTypeGenerator.cs
While there are a lot of backslashes in csproj files everywhere, msbuild seems to do a decent job at converting them automatically.
The ones in CS files directly on the other hand, cause files with literal backslashes in their names to be generated.
```
fernie@tiberius /tmp/scratch/csharpier/Src (git)-[master] % git status 
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   CSharpier.Tests/EncodingTests/USC2LEBOM.actual.cst
modified:   CSharpier.Tests/Samples/AllInOne.json
modified:   CSharpier.Tests/Samples/Scratch.json
Untracked files:
(use "git add <file>..." to include in what will be committed) …
```
> Fix files with backslashes being generated on Linux

- Src/CSharpier/Program.cs
Turns out charset detection fails on empty files, causing CSharpier to crash with a `NullReferenceException`.
> Fix crash on empty files

- Src/CSharpier.Tests/TestFiles/BinaryExpression/StringConcatenation.cst
- Src/CSharpier.Tests/TestFiles/BinaryExpression/_BinaryExpressionTests.cs
- Src/CSharpier/Printer/BinaryExpressionSyntax.cs
Much like the bitwise operators, it makes sense to break around `+` because it's used for string concatenations.
> Make string concatenations wrap

- Src/CSharpier.Tests/TestFiles/Directives/Directives.cst
- Src/CSharpier/SyntaxPrinter/SyntaxTokens.cs
The previous fix wasn't applied to regions. Plus this case was indenting when it shouldn't.
> Another newline directive edge case.

- Src/CSharpier/FileReader.cs
> re-add async file reads

- Src/CSharpier.Tests/TestFiles/ForEachStatement/ForEachStatements.cst
- Src/CSharpier.Tests/TestFiles/ForStatement/ForStatements.cst
- Src/CSharpier.Tests/TestFiles/IfStatement/IfStatements.cst
- Src/CSharpier.Tests/TestFiles/WhileStatement/WhileStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForEachStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IfStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/WhileStatement.cs
closes #202
I did this for for, foreach, if/else if, do and while. I can't think of any other places this would be needed.
> dealing with loops without braces

- .github/workflows/validatePR.yml
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/LineEndingTests.cs
- Src/CSharpier.Tests/SyntaxNodeComparerTests.cs
- Src/CSharpier.Tests/TestFiles/StringLiteral/VerbatimStrings.cst
- Src/CSharpier/CommandLineFormatter.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
also fixing some issues with unit tests
closes #221
> fixing issue with interpolated verbatim string literal

- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/TestFiles/Directives/Directives.cst
- Src/CSharpier/DocPrinter/DocPrinter.cs
> Fixing bug with directive following a trailing comment getting extra indentation

- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/DocSerializer.cs
- Src/CSharpier/DocTypes/HardLine.cs
> fixing some more edge cases with leading comments affecting breaking

- CSharpier.sln
- Src/CSharpier.MsBuild/README.md
- Src/CSharpier/CommandLineFormatter.cs
closes #228
dotnet watch run gets stuck in a loop because it detects a file write even if the contents of the file did not change with that write.
#241 was created so we can hopefully modify CSharpier.MSBuild in the future to only format files that were changed.
> Only write files if they changed

- Src/CSharpier.Benchmarks/Program.cs
- Src/CSharpier.Tests/TestFiles/Directives/Directives.cst
- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/DocSerializer.cs
- Src/CSharpier/SyntaxNodeComparer.generated.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
- Src/Worker/Ignored.cs
refactor docprinter a little
ignore some properties in syntaxNodeComparer so that it gives you a better indication of the code that is failing the validation
> fixing another edge case related to comments + directives

- Src/CSharpier.Tests/TestFiles/ClassDeclaration/ClassDeclarations.cst
- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseList.cs
Format the inherited interfaces and base classes according to https://github.com/belav/csharpier/issues/189#issuecomment-847140886. 
The new style is like this
```csharp
public class AClass : 
AReallyLongBuilder<BuilderType>, 
IAnotherReallyBuilder<AnotherType> { }
```
Closes #189
> Better format interfaces and base classes

- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/TestFiles/ClassDeclaration/ClassDeclarations.cst
- Src/CSharpier.Tests/TestFiles/RecordDeclaration/RecordDeclarations.cst
- Src/CSharpier/DocPrinter/DocFitter.cs
- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/DocPrinter/Indent.cs
- Src/CSharpier/DocSerializer.cs
- Src/CSharpier/DocTypes/Align.cs
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/DocTypes/StringDoc.cs
- Src/CSharpier/DocTypes/Trim.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseList.cs
This implements a basic version of the align doc type. The prettier version does a lot more, but we can keep it simple until we need to add the extra complexity.
This also uses align to handle formatting ClassDeclaration with BaseLists to get them looking good with ConstraintClauses
closes #276
closes #275
> Implementing align doc type + using it for classes

- Src/CSharpier.Tests/TestFiles/ClassDeclaration/ClassDeclarations.cst
- Src/CSharpier.Tests/TestFiles/ConstructorDeclaration/ConstructorDeclarations.cst
- Src/CSharpier.Tests/TestFiles/DelegateDeclaration/DelegateDeclarations.cst
- Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/TestFiles/TypeParameterConstraintClause/TypeParameterConstraintClauses.cst
- Src/CSharpier/SyntaxPrinter/ConstraintClauses.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ConstructorInitializer.cs
If there is only one generic constraint, we try to keep it on the same line. If more one, they're broken up.
As for the constructor initialiser, it's kept on the same line as the ending brace of the arguments.
Closes #94
> Better print generic methods and constructors

- Src/CSharpier.Tests/TestFiles/FieldDeclaration/FieldDeclarations.cst
- Src/CSharpier.Tests/TestFiles/ObjectCreationExpression/ObjectCreationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ObjectCreationExpression.cs
> Modify ObjectCreationExpression with Initializer to use space brace

- Src/CSharpier.Tests/TestFiles/AttributeList/AttributeLists.cst
- Src/CSharpier.Tests/TestFiles/ObnoxiousEdgeCases/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/TestFiles/StringLiteral/StringLiterals.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AttributeList.cs
> Break long attributes consistently

- .github/workflows/playground_publish.yml
This ensures that the published playground site will be running the most recent release, it will not be running prerelease code.
closes #224
> Only publish the playground when a new tag is pushed

- Src/CSharpier.Tests/TestFiles/CheckedStatement/CheckedStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CheckedExpression.cs
> Print checked the same way as an invocationExpression

- Src/CSharpier.Tests/TestFiles/AssignmentExpression/AssignmentExpressions.cst
- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AssignmentExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/VariableDeclaration.cs
> Use common logic for printing rhs of assignment expressions

- .gitignore
- Src/CSharpier.Tests/TestFiles/AttributeList/AttributeLists.cst
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Parameter.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ParameterList.cs
Added breaking and tab logic to parameter when attribute is involved, while grouping the parameter itself as that allowed for a custom break. Removed unnecessary `using` statement.
Ignored `.vscode` for people who think that it is an IDE.
Fixes #204.
Fixes #334.
> Break and Tab Parameters with Attributes

- Src/CSharpier.Tests/TestFiles/FieldDeclaration/FieldDeclarations.cst
- Src/CSharpier.Tests/TestFiles/ParenthesizedLambdaExpression/ParenthesizedLambdaExpressions.cst
- Src/CSharpier.Tests/TestFiles/VariableDeclaration/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/ArgumentListLikeSyntax.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ParenthesizedLambdaExpression.cs
When printing expression bodies - indent and group the contents to handle edge cases like BinaryExpressions in them.
This also cleans up the formatting of expression bodies that used to break onto multiple lines when they had an InvocationExpression.
closes #176
> Improving the formatting of lambda's with expression bodies.

- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/SyntaxNodeComparerTests.cs
- Src/CSharpier/SyntaxNodeComparer.cs
> Fix issue with validation failing for mismatched line endings in verbatim strings

- Src/CSharpier.Tests/TestFiles/InitializerExpression/InitializerExpressions.cst
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ImplicitObjectCreationExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ObjectCreationExpression.cs
> Fixing some edge cases for initializers

- CSharpier.sln
- Scripts/CreateReviewCodePRs.ps1
- Scripts/CreateTestingPR.ps1
This relates to #286, but doesn't yet close it. Ideally this would run automatically as PRs are created, and comment on those PRs.
> Scripting way to test formatting repo

- Src/CSharpier.Tests/TestFiles/SwitchExpression/SwitchExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchExpression.cs
SwitchExpressions will now break + align 2 the => section.
Some of the test cases still look a little ugly because the Pattern/Expression of each arm are not indented. That indentation will be handled as part of BinaryExpressions #37 or BinaryPattern #349
closes #237
> Better SwitchExpression Formatting

- Docs/Configuration.md
- README.md
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
- Src/CSharpier/ConfigurationFileOptions.cs
If csharpier is opinionated, it shouldn't offer options beyond print width.
This hides those options, but doesn't yet clean up the code related to them.
closes #358
> Remove most configuration options

- Src/CSharpier.Tests/TestFiles/MethodDeclaration/MethodDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Block.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Make sure empty block doesn't break on method declaration

- Src/CSharpier.Tests/TestFiles/TypeParameterConstraintClause/TypeParameterConstraintClauses.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
> Break after type constraints for method declarations. It keeps things more consistent

- Src/CSharpier.Tests/TestFiles/SwitchExpression/SwitchExpressions.cst
- Src/CSharpier.Tests/TestFiles/SwitchStatement/SwitchStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CasePatternSwitchLabel.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CaseSwitchLabel.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/DefaultSwitchLabel.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchStatement.cs
Respect empty lines between case statements and switch expression patterns
Closes #383
> Respect empty lines between case statements and switch expression patterns

- Src/CSharpier.Tests/FormattingTests/TestFiles/IsPatternExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/SwitchExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/SwitchStatements.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BinaryPattern.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IsPatternExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/NameColon.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
> Pattern matching edge cases

- Src/CSharpier.Tests/FormattingTests/TestFiles/InvocationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> BaseExpression should merge in InvocationExpression

- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/AttributeLists.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/Comments.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/EnumDeclarations.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/UsingStatements.cst
- Src/CSharpier/DocPrinter/DocPrinter.cs
> Ensure files end with a single new line

- Src/CSharpier.Tests/FormattingTests/TestFiles/EnumDeclarationComments.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/EnumDeclarationComments.expected.cst
- Src/CSharpier/DocPrinter/PropagateBreaks.cs
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/EnumMemberDeclaration.cs
> Keep lines above comments in enums

- Scripts/CreateTestingPR.ps1
- Src/CSharpier.Tests/FormattingTests/TestFiles/ConditionalExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/InitializerExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/VariableDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ConditionalExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Fixing indentation issues with conditionals inside initializers

- .gitignore
- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/Program.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/ClassDeclarations_EdgeCase.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/ClassDeclarations_EdgeCase.expected.cst
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/DebugLogger.cs
- Src/CSharpier/SyntaxPrinter/PreprocessorSymbols.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
> If file has no preprocessor symbols, only format it once

- Src/CSharpier.Generators/NodePrinterGenerator.sbntxt
- Src/CSharpier.Playground/ClientApp/src/FormatCode.ts
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore_Dont.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/CSharpierIgnore_Dont.expected.cst
- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
> Implement csharpier-ignore for some node types

- Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
closes #565
https://github.com/belav/csharpier/issues/459 has a note to update the readme when 0.15.0 is released.
> Use .net6 for msbuild library

- Src/CSharpier.Tests/FormattingTests/TestFiles/InvocationExpressions.cst
- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Make sure null conditionals break like regular expressions

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/ConfigurationFileOptions.cs
- Src/CSharpier.Cli/IgnoreFile.cs
> Drastically speed up formatting when ignore or config file exist.

- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ProcessHelper.java
For #610
On Mac, the `dotnet` binary isn't available to the `ProcessBuilder`. I added the binary to the `PATH`. I wanted to be mindful of ARM/x64 so the `PATH` exposes the ARM build first and the x64 secondly. However, the `PATH` variable isn't available to the `ProcessBuilder`, but it is for any spawned processes. With that in mind, I updated the`ProcessHelper` to wrap the `command` argument within the OS's default shell.
**Alternatives**
- Add a `.GetDotNetBinary()` method that returned `/usr/local/share/dotnet/dotnet` on Mac.
- This worked fine, but it wouldn't support x64 binaries on the M1 Mac, so I decided against it.
- Get the binary in use from Rider 
- I couldn't figure out how to get this to work, but if we could make it happen, I believe it'd be the best option.
> fix: macos rider

- .github/workflows/format_repositories.yml
- .github/workflows/publish_nuget.yml
- .github/workflows/validate_pull_request.yml
- global.json
The github actions are failing due to the source generators appearing to use a newer version of roslyn.
> Fixing github actions

- Src/CSharpier.Cli/CommandLineFormatter.cs
I was using CSharpier in a project whose directory name contained a period, e.g., `/home/jsanchezio/Documents/Repos/My.Project/`, and despite having a `.csharpierignore` file, it would still report files excluded by the ignore as unformatted. I was running the command as `dotnet csharpier --check .` After some investigation, it turns out `fileSystem.Path.GetExtension(directoryOrFile)` would return the path after the period, e.g., `.Project`. This change alters the command to instead check if the `directoryOrFile` is a directory that exists and reacts accordingly.
After I discovered the issue, I renamed my project's folder name and all worked well. However, in CI environments there is no guarantee that a `.` won't be in the path, so I figured it was best to handle it within CSharpier.
> fix: ignore file detection when directory contains period

- Src/CSharpier.Tests/FormattingTests/TestFiles/InvocationExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Dealing with an edge case for conditional access

- Src/CSharpier.Tests/FormattingTests/TestFiles/InvocationExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/ObnoxiousEdgeCases.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/ParenthesizedLambdaExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/SimpleLambdaExpressions.cst
- Src/CSharpier/SyntaxPrinter/ArgumentListLikeSyntax.cs
This handles the simple cases, #672 will take care of some more complex cases.
closes #669
> Better lambda indent

- Docs/Editors.md
- Src/Website/docs/Editors.md
I recently merged a PR to [neoformat](https://github.com/sbdchd/neoformat) to support `csharpier` out of the box. This PR updates the editor plugin docs to reference it as an option for `neovim` users.
[Referenced neoformat PR](https://github.com/sbdchd/neoformat/pull/428)
> docs: Added neovim plugin option

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/FormattingCache.cs
- Src/CSharpier/DebugLogger.cs
closes #728
I'm not in love with this fix, but it will ensure that csharpier doesn't crash when multiple csharpier processes try to write the formatting cache at the same time. Maybe the waiting time doubling is overkill, and it should just wait 1ms and try 10 times. 20 times? I'll think about it more again in the morning. I'd like to get a fix out tomorrow because I'm going on vacation for 5 days after tomorrow.
One downside is that in the case of 4 projects being formatted at the same time, the first time csharpier runs using MSbuild if all 4 build at the same time only 1 of the projects will end up in the cache. But after you build 4 times, chances are good that the cache will catch up. The other option would be to reread the cache before writing it and tying to merge things together. …
> Potential fix for multiple processes trying to save formatting cache

- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AwaitExpression.cs
Hi, @belav! I believe this PR fixes #740, but I am not sure whether my solution is optimal, nor whether it's complete. I would really appreciate your feedback and any direction if this is not adequate.
Thanks!
> Add line when await precedes query expression

- Docs/ContinuousIntegration.md
- Fixed the format of the dotnet local tool command to be as shown in the .NET docs.
- Fixed typo for "github actions"
I'm not good at dotnet, but the current actions example didn't really work.
I fix the command to work by referring to the [.NET docs](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use).
> docs: Fix the CI example codes to be valid

- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
> Fix for subfolders in node_modules

- Src/CSharpier.Tests/FormattingTests/TestFiles/ConstructorDeclarations.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
> Put constructor initializer on new line

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
`error  : Specified condition "$(CSharpier_Check)" evaluates to "" instead of a boolean.  C:\Users\<username>\.nuget\packages\csharpier.msbuild\0.21.0\build\CSharpier.MsBuild.targets`
This error makes it impossible to unload and reload projects in a Multi Project Solution.
> Fixed Condition Error

- .github/workflows/validate_pull_request.yml
- Directory.Packages.props
- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CSharpier.Cli.csproj
- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/FileReader.cs
- Src/CSharpier.Tests/CSharpier.Tests.csproj
- Src/CSharpier.Tests/FormattingTests/TestFiles/FileEncodingAnsi.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/FileEncoding_UTF8.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/FileEncoding_UTF8BOM.cst
closes #768
Previously UTF.Unknown was used to try to determine file encodings. This was problematic because if a file was too small, it would end up with several possible encodings. The encoding it considered most likely was not always correct. As opposed to trying to read a file as each encoding type, CSharpier now only supports UTF8 files. This is consistent with the IDE plugins, which stream files to CSharpier as UTF8. If a file is UTF8-BOM, it will retain the BOM.
> Only read files that are UTF8 or UTF8 BOM

- CHANGELOG.md
- CSharpier.Build.props
- Docs/MSBuild.md
- Src/CSharpier.MsBuild/README.md
- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
Checks if a compatible target framework is used. If not, .NET 7 is used.
This prevents error messages like the following.
```
C:\Users\<username>\.nuget\packages\csharpier.msbuild\0.22.0\build\../tools/csharpier/netstandard2.0/dotnet-csharpier.dll  C:\sources\Test1\src\Console1" exited with code 1.
```
> Checks compatible target framework

- .pre-commit-hooks.yaml
- Docs/Pre-commit.md
- Src/Website/docs/Pre-commit.md
- global.json
.NET pre-commit hooks rely on `dotnet pack`, which uses the .NET SDK version specified in `global.json`. Relax the .NET SDK version constraint from ~7.0.100 to ^7.0.100, maximizing compatibility.
> Offer a pre-commit hook that runs the .NET tool

- Docs/CLI.md
- Docs/Configuration.md
- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/CommandLineOptions.cs
- Src/CSharpier.Cli/ConfigurationFileOptions.cs
- Src/CSharpier.Cli/Program.cs
- Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
- Src/CSharpier.Tests/ConfigurationFileOptionsTests.cs
> Support for passing a config file to csharpier

- Src/CSharpier.Tests/CSharpier.Tests.csproj
- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions_RemoveSpaces.cst
- Src/CSharpier.Tests/FormattingTests/TestFiles/QueryExpressions_RemoveSpaces.expected.cst
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/GroupClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/JoinClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/LetClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/OrderByClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SelectClause.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/WhereClause.cs
> Allow empty lines in query syntax

- .pre-commit-hooks.yaml
- Docs/Pre-commit.md
- Src/Website/docs/Pre-commit.md
Resolves #820.
pre-commit doesn't currently support additional dependencies for .NET hooks, so the CSharpier hook didn't work, because CSharpier relies on additional dependencies. Document how to run CSharpier via MegaLinter's pre-commit hooks or a standalone local pre-commit hook.
> Remove pre-commit hook; document options (#820)

- .github/workflows/format_repositories.yml
- .github/workflows/publish_nuget.yml
- .github/workflows/validate_pull_request.yml
- Directory.Packages.props
- Dockerfile
- Src/CSharpier.FakeGenerators/CSharpier.FakeGenerators.csproj
- Src/CSharpier.Generators/CSharpier.Generators.csproj
- Src/CSharpier.Tests.Generators/CSharpier.Tests.Generators.csproj
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ClassDeclarations.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives.test
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/SyntaxNodeComparer.generated.cs
- Src/CSharpier/SyntaxNodeJsonWriter.generated.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/UsingDirective.cs
- Src/SyntaxFinder/SyntaxFinder.csproj
- global.json
> Supporting c# 12

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/ChangeLog.md
According to the [official docs](https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022) there should be only a need for a specific InstallationTarget to support ARM64 version of Visual Studio. 
I've added it and it seems to be working correctly in my experimental release.
I know that I am probably the only user of ARM version of VS2022, but still I'd really like to use CSharpier ;)
> Add support for ARM64 version of VS2022

- Src/CSharpier.Tests/Utilities/StringDifferTests.cs
- Src/CSharpier/Utilities/StringDiffer.cs
> Only make whitespace visible on otherwise empty lines or if it is trailing.

- Src/CSharpier.Cli/EditorConfig/ConfigFileParser.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
The spec very clearly states that comments are supported. Without this fix a basic config file like the example given on the EditorConfig website will cause a crash.
```
root = true
[*]
end_of_line = lf
insert_final_newline = true
```
Spec: https://spec.editorconfig.org/#file-format
> fix: support EditorConfig comments

- .gitignore
- Src/CSharpier.MsBuild.Test/CSharpier.MsBuild.Test.sln
- Src/CSharpier.MsBuild/README.md
- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
> Ensure that compilation errors surface properly when building a project with CSharpier.msbuild in debug

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/StructDeclarations.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
closes #969
looks like I missed that structs could also have primary constructors when I made this work for classes.
> Formatting struct primary constructor

- .github/workflows/format_repositories.yml
- .github/workflows/publish_nuget.yml
- .github/workflows/validate_pull_request.yml
It looks like the newest setup-dotnet will read the global.json file, which appears to eliminate the need to specify the version at all
> Cleaning up action

- Docs/Configuration.md
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
> An existing csharpierrc file always takes priority over editorconfig

- Src/CSharpier.Cli/EditorConfig/ConfigFileParser.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
> fix issues with duplicated editorconfig sections, handle failures parsing editorconfigs

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsGlobalSystemToTop.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsGlobalSystemToTop.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsMixedCorrectly.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortsMixedCorrectly.test
- Src/CSharpier/SyntaxPrinter/UsingDirectives.cs
> Sort global System usings before other global usings

- Docs/MSBuild.md
- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
> Dotnet 8 support

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcess.ts
- Src/CSharpier.VSCode/src/CSharpierProcessPipeMultipleFiles.ts
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/CustomPathInstaller.ts
- Src/CSharpier.VSCode/src/Extension.ts
> Fixing a couple vscode issues

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
Relevant issues:
https://github.com/belav/csharpier/issues/1027
https://github.com/belav/csharpier/issues/1022
https://github.com/belav/csharpier/issues/1019
Instead of using the current TargetFramework that is being built as part of the MSBuild process we use the SDK version that the MSBuild process is using to determine which version of the CSharpier dotnet tool we should use.
The goal is to allow those who only keep one version of an SDK and runtime installed on their machine the ability to use CSharpier in a more reliable manner.
> Use NETCoreSdkVersion to determine which CSharpier tool version to use during builds

- Src/CSharpier.Cli/EditorConfig/EditorConfigParser.cs
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
This will resolves issue #1023.
Any .editorconfig file included in the .csharpierignore file will not be parsed. By default we ignore everything in node_modules, but it still tries to parse the .editconfig file.
> Ignore .editorconfig file included in the .csharpierignore file

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/EditorConfig/EditorConfigParser.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Cli/Program.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
This is gonna cause conflicts with #1030
> Optimize editorconfig lookups when piping files

- Src/CSharpier/SyntaxPrinter/UsingDirectives.cs
Fixes #1051.
I used `Ordinal` here just because it was what Rider suggested:
> Sort usings with Ordinal culture (#1051)

- Docs/Installation.md
There was no clear documentation of updating the tool once it was installed. This commit adds this information to the installation documentation.
> Update Installation.md with tool update instructions

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortIgnoreCasing.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UsingDirectives_SortIgnoreCasing.test
- Src/CSharpier/SyntaxPrinter/UsingDirectives.cs
Fixes #1061
`Newtonsoft.Json` should be sorted before `NSubstitute`
> Sort usings with OrdinalIgnoreCase

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CollectionExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/CollectionExpression.cs
Closes #1063 
Avoids adding a newline before a `CollectionExpressionSyntax` when its parent is an `EqualsValueClause` whose own parent is a `PropertyDeclarationSyntax`.
> Remove extra newline for collection expression property initializers

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/ArgumentLists.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/BinaryExpressions.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChain_PropertiesConsistent.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SimpleLambdaExpressions.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/VariableDeclarations.test
- Src/CSharpier/SyntaxPrinter/ArgumentListLikeSyntax.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Argument.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ParenthesizedLambdaExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SimpleLambdaExpression.cs
> feat: Improve formatting of lambda expressions

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChain_PropertiesConsistent.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Keep property with method

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChain_PropertiesConsistent.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SimpleLambdaExpressions.test
- Src/CSharpier/SyntaxPrinter/ArgumentListLikeSyntax.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SimpleLambdaExpression.cs
Fix the first and third bugs described in #1077
> fix: bugs from #1066

- Src/CSharpier/DocPrinter/DocFitter.cs
While I was working on the fixes for #1077, I needed to debug `DocFitter`. There is the long chained if-else and when you press the `Step over` button in RIder the debugger stops on a condition of each branch, but in a switch statement the debugger jumps right to the executed branch and it speed up debugging.
I don't mind if the PR will be rejected. It contains only syntax changes and doesn't modify the logic of `DocFitter`
> refactor: Use switches instead of if-else in DocFitter

- Src/CSharpier.Cli.Tests/CliTests.cs
* When the tests run in an environment with e.g. a German operating system "expected" is translated, so this test fails.
> Fix tests for environments with another culture

- Src/CSharpier.Generators/CSharpier.Generators.csproj
- Src/CSharpier.Tests.Generators/CSharpier.Tests.Generators.csproj
* Changed the TFM to netstandard2.0 because the Generator could not be loaded in Rider
* Reading the docs it says, that it needs to target netstandard2.0 https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview#get-started-with-source-generators
> TargetFramework netstandard2.0 for SourceGenerators

- Tests/MsBuild/Run.ps1
This should ensure that we can add and try out further test scenarios without any restrictions. In perspective e.g. `net9.0`
> fix: Removed magic value from the MSBuild scenarios creation

- docs/EditorsTroubleshooting.md
Update casing of `$HOME` because environment variables are case sensitive in Linux.
> Minor update to EditorsTroubleshooting.md

- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
closes #1153
I did add a test case, but accidentally went to main with it when I was dedenting [MemberChains.test](https://github.com/belav/csharpier/blob/main/Src/CSharpier.Tests/FormattingTests/TestFiles/cs/MemberChains.test)
```c#
// 0.27.1
o
.Property.CallMethod(
someParameter_____________________________,
someParameter_____________________________
)
.CallMethod()
.CallMethod();
// 0.27.2
o.Property.CallMethod(
someParameter_____________________________,
someParameter_____________________________
)
.CallMethod()
.CallMethod();
> Fixing regression from 0.27.1 with invocations

- Src/CSharpier.Benchmarks/Program.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Playground/ClientApp/src/AppContext.ts
- Src/CSharpier.Playground/ClientApp/src/Controls.tsx
- Src/CSharpier.Playground/ClientApp/src/FormatCode.ts
- Src/CSharpier.Playground/Controllers/FormatController.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/FormattingTests/BaseTest.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/csx/Basics.test
- Src/CSharpier.Tests/Samples/Samples.cs
- Src/CSharpier.Tests/SyntaxNodeComparerTests.cs
- Src/CSharpier/CSharpFormatter.cs
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/SyntaxNodeComparer.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Actually format csx files

- Src/CSharpier.Tests/CodeFormatterTests.cs
- Src/CSharpier/CodeFormatter.cs
- Src/CSharpier/CodeFormatterOptions.cs
- Src/CSharpier/EndOfLine.cs
- Src/CSharpier/PrinterOptions.cs
- Src/CSharpier/PublicAPI.Unshipped.txt
Tried to incorporate your feedback. Personally think it's just fine to have an enum with just two values, so I went along with it. Had to make EndOfLine public as well, hence I also moved it out of PrinterOptions.cs, but wasn't sure where to place it.
Not familiar with how that PublicAPI.Unshipped.txt stuff works, but I let my IDE update it. Let me know if it's all wrong :)
> Sync exposed CodeFormatterOptions with currently supported cli options

- Src/CSharpier.Tests/DocPrinterTests.cs
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/RawStringLiterals.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/StringLiterals.test
- Src/CSharpier/DocPrinter/PropagateBreaks.cs
- Src/CSharpier/SyntaxNodeExtensions.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InterpolatedStringExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
> Fixing issues with weird indent on raw string literals as arguments

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SpreadElements.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SpreadElement.cs
- Src/SyntaxFinder/Program.cs
- Src/SyntaxFinder/SpreadWalker.cs
> Adding formatting for spread element

- CHANGELOG.md
- CSharpier.sln
- Nuget/Build.props
- Src/Website/docs/Editors.md
> Releasing 0.27.3

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/README.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessPipeMultipleFiles.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessProvider.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessServer.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessSingleFile.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierSettingsComponent.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierStartup.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CustomPathInstaller.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/DotNetProvider.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/InstallGlobalAction.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/InstallLocalAction.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/InstallerService.java
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/ProcessHelper.java
- Src/CSharpier.Rider/src/main/resources/META-INF/plugin.xml
This makes use RiderDotNetActiveRuntimeHost to find the path to the dotnet exe, and sets DOTNET_ROOT where appropriate. This should remove any need for the PATH to be correct.
closes #893
> Better support for dotnet commands.

- Src/CSharpier.Cli/EditorConfig/ConfigFileParser.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
> Gracefully deal with bad editorconfigs

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package-lock.json
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcessPipeMultipleFiles.ts
- Src/CSharpier.VSCode/src/CSharpierProcessProvider.ts
- Src/CSharpier.VSCode/src/CSharpierProcessServer.ts
- Src/CSharpier.VSCode/src/CSharpierProcessSingleFile.ts
- Src/CSharpier.VSCode/src/Extension.ts
- Src/CSharpier.VSCode/src/FormattingService.ts
- Src/CSharpier.VSCode/src/ICSharpierProcess.ts
- Src/CSharpier.VSCode/src/NullCSharpierProcess.ts
> VSCode - Use CSharpier Http Server for 0.28.0+

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcessServer.ts
> Fix issue with csharpier server not using dotnet root

- Src/CSharpier.Rider/CHANGELOG.md
- Src/CSharpier.Rider/gradle.properties
- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessServer.java
- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/CSharpierProcessServer.ts
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessServer.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> CSharpier server was starting on 127.0.0.1, if localhost resolved to ::1 extensions could not format

- Src/CSharpier.Tests/CodeFormatterTests.cs
- Src/CSharpier/Utilities/CharacterSizeCalculator.cs
- Src/CSharpier/Utilities/StringExtensions.cs
> Consider wide unicode characters to be size of 2

- Src/CSharpier.Cli/Server/ServerFormatter.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierOptions.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessServer.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Fall back to VS looking for port. Add way to disable csharpier server.

- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
The VS extension is not able to work with preview versions. If you have a version like 0.27.3-beta, then the extension does not work. This code is fixing this issue. It allows to work with preview versions.
> Allow to work with semantic versioning

- Src/CSharpier.Cli/CommandLineOptions.cs
- Src/Website/docs/CLI.md
- docs/CLI.md
> Fix CLI message regarding directoryOrFile

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.props
At this point `CSharpier_Check` can be already set. For example: `Directory.Build.props` imported before `CSharpier.MsBuild.props`, and `CSharpier_Check` can be set here. Set default value only when current is empty.
> Do not overwrite `CSharpier_Check`, when already set.

- Src/CSharpier.Cli.Tests/ServerTests.cs
- Src/CSharpier.Cli/Server/ServerFormatter.cs
- Src/CSharpier/DebugLogger.cs
closes #1324
I wish I remembered what led me to this nreco package. Maybe because serilog seemed overboard and I wanted something super lightweight.
> Support for multiple csharpier servers running at the same time, have them write to a file based on the port.

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/CSharpierIgnore.test
- Src/CSharpier/SyntaxPrinter/MembersWithForcedLines.cs
- Src/CSharpier/SyntaxPrinter/SeparatedSyntaxList.cs
- docs/Ignore.md
> Adding support for csharpier-ignore-start in object initializers

- Src/CSharpier.Cli/CSharpier.Cli.csproj
Fixes part of #1321 
With this change it should be possible to just call csharpier instead of dotnet csharpier
> Add csharpier as ToolCommandName

- .github/workflows/format_repositories.yml
- .run/Playground.run.xml
- Directory.Build.props
- Scripts/RunLinuxTests.ps1
- Src/CSharpier.Cli/CSharpier.Cli.csproj
- Src/CSharpier.FakeGenerators/SyntaxNodeComparerGenerator.cs
- Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
- Src/CSharpier.Tests/CSharpier.Tests.csproj
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/AllowsRefStruct.test
- Src/CSharpier/CSharpier.csproj
- Src/CSharpier/SyntaxNodeComparer.generated.cs
- Src/CSharpier/SyntaxNodeJsonWriter.generated.cs
- Src/SyntaxFinder/SyntaxFinder.csproj
- docs/MSBuild.md
- global.json
closes #1318
Net6 is EOL nov 12th. 1.0 will probably be released after that.
> Adding net9/c#13 support. Drop support for net6/7

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/InitializerExpressions.test
- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
> get implicit object creation consistent with explicit creation

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierOptions.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
This fixes #1367. 
The `.vs/$(SolutionName)/v17/csharpier.json` file is now watched for changes and will reload the configuration when the file is changed.
> VS Extension now hot reloads its config

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
Use current `dotnet` binary from `DOTNET_HOST_PATH` instead of just `dotnet`.
Reasons:
1. Global (in `PATH`) may not exist (when used _Binaries_, but not _Installers_).
2. Global can have different runtime version.
3. Consistent with outer tools (`csc` for example).
https://github.com/dotnet/roslyn/blob/324fd25331c969cd742ba68eee09ffd4b6fd29e3/src/Compilers/Shared/RuntimeHostInfo.cs#L61-L64
4. It is documented to be used for that purpose.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_host_path
> Use current `dotnet` host instead of global

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
As CSharpier currently does not output error messages in MSBuild compatible format, adapt Exec options to current error format. Should fix #1357.
> Adapt to current error format

- .csharpierignore
- .github/workflows/validate_pull_request.yml
- Src/CSharpier.MsBuild/README.md
- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
- Tests/MsBuild/Directory.Build.props
- Tests/MsBuild/Run.ps1
- Tests/MsBuild/Scenarios.json
- Tests/MsBuild/TestCases/FileThatCantCompileCausesOneError/FileWithCompileError.cs
- Tests/MsBuild/TestCases/FileThatCantCompileCausesOneError/Project.csproj
- Tests/MsBuild/TestCases/UnformattedFileCausesError/Project.csproj
- Tests/MsBuild/TestCases/UnformattedFileCausesError/UnformattedFile.cs
- Tests/MsBuild/nuget.config
The changes for https://github.com/belav/csharpier/pull/1311 seem to work in windows, but cause problems in linux. Files that aren't formatted are no longer treated as errors.
closes #1357
> Msbuild unformatted files are no longer treated as error on linux

- Src/CSharpier.VSCode/CHANGELOG.md
- Src/CSharpier.VSCode/package.json
- Src/CSharpier.VSCode/src/DiagnosticsService.ts
> Adding an option to disable diagnostics for unformatted code.

- Src/CSharpier.VisualStudio/CSharpier.VisualStudio/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudio2019/source.extension.vsixmanifest
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierPackage.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/CSharpierProcessProvider.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpier.cs
- Src/CSharpier.VisualStudio/CSharpier.VisualStudioShared/ReformatWithCSharpierOnSave.cs
- Src/CSharpier.VisualStudio/ChangeLog.md
> Avoid eagerly warming csharpier, doesn't seem to be a good way to delay that and it is possibly slowing down VS startup.

- Src/CSharpier.Cli/Options/ConfigurationFileOptions.cs
- Src/CSharpier.Tests/Cli/Options/ConfigFileParserTests.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
- docs/Configuration.md
> Renaming TabWidth to IndentSize

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/TrailingComma_TrailingComments.expected.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/TrailingComma_TrailingComments.test
- Src/CSharpier/SyntaxPrinter/MembersWithForcedLines.cs
> fixing trailing comma + trailing comment issue on enums

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Cli/Server/CSharpierServiceImplementation.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier/DebugLogger.cs
We only want that error/warning if someone directly requests to format a file that csharpier does not support. Formatting a directory assumes that you only want to format files that are supported and/or have a defined formatter in the config.
> Fixing issue with unsupported file error being shown for all files that csharpier can't format in a given directory.

- Src/Website/docs/Configuration.md
- docs/Configuration.md
Added anchor link to the EditConfig reference.
> Update Configuration.md to link to EditorConfig section

- Src/CSharpier.Cli.Tests/CliTests.cs
The test `CliTests.Should_Return_Error_When_No_DirectoryOrFile_And_Not_Piping_StdIn` was consistently failing when executed via the `dotnet test` command.
This issue appears to have been caused by CliWrap, which initializes `ProcessStartInfo` with `RedirectStandardInput = true` by default. This behavior interfered with the test, as it relies on `Console.IsInputRedirected` being `false`.
This patch updates the test to use `ProcessStartInfo` directly instead of relying on CliWrap. This ensures that `RedirectStandardInput` is explicitly set to `false`.
> Fix: `dotnet test` failure in `CliTests.Should_Return_Error_When_No_DirectoryOrFile_And_Not_Piping_StdIn`

- Src/CSharpier.Cli/PipeMultipleFilesFormatter.cs
- Src/CSharpier.Cli/Server/CSharpierServiceImplementation.cs
This fixes the issue where we pass /temp/test.cs as the "warmup" file path, and then that path is treated differently later on in the code. Calling GetFullPath on it will convert it to c:/temp/test.cs on windows.
closes #1447
> Treat the path we get from the format request as a full path

- Src/CSharpier/Utilities/StringExtensions.cs
`value.Sum(` allocates a `CharEnumerator` instance, manually looping prevents the allocation. Saves around 5 MB on the benchmark iirc 5% of total allocations.
This could be further improved by using a SIMD implementation of `CharacterSizeCalculator.CalculateWidth`, this is extremely micro benchmarky tho 😅 
| Method                                  | Mean          | Error        | StdDev       | Gen0       | Gen1      | Gen2      | Allocated    |
|---------------------------------------- |--------------:|-------------:|-------------:|-----------:|----------:|----------:|-------------:|
| Default_CodeFormatter                   | 170,091.68 us | 3,367.421 us | 5,437.757 us | 11000.0000 | 4000.0000 | 1000.0000 | 103844.49 KB |
| Default_SyntaxNodeComparer              |   1,732.65 us | …
> feat: use foreach loop in `GetPrintedWidth` to prevent `CharEnumerator` allocations

- Src/CSharpier/Formatters/CSharp/PreprocessorSymbols.cs
Similar to #1485, use a manual `foreach` where loop to prevent boxing of `SyntaxTriviaList`, `SyntaxTriviaList.EnumeratorImpl` and `WhereIterator`.
> feat: manual `Where` loop to prevent boxing and enumerator allocation

- Src/CSharpier/Utilities/ListExtensions.cs
Creates an extension method that overloads `Any(this SyntaxTriviaList)` this uses the struct `SyntaxTriviaList.Enumerator` to iterate, instead of allocating the class `SyntaxTriviaList.EnumeratorImpl : IEnumerator<SyntaxTrivia>` and boxing `SyntaxTrviaList`.
Saves around 11% of memory aka 11MB on the benchmark.
| Method                                  | Mean          | Error        | StdDev       | Median        | Gen0       | Gen1      | Gen2      | Allocated   |
|---------------------------------------- |--------------:|-------------:|-------------:|--------------:|-----------:|----------:|----------:|------------:|
| Default_CodeFormatter                   | 187,771.22 us | 3,718.757 us | 6,705.686 us | 187,214.50 us | 11000.0000 | 4000.0000 | 1000.0000 | 98124.57 KB |
| …
> feat: create an overload for `Any( SyntaxTriviaList` to prevent allocations

- Src/CSharpier/SyntaxPrinter/Token.cs
Convert linq to code to prevent closure allocation to capture the `Regex` value. This removes a 1 MB `DisplayClass` closure object and a 2.4MB `Func<SyntaxTrivia, bool>`, not sure why this removes both a display class and a func object 🤷 
No idea why dotMemory claims that the method isn't allocating all of objects, I guess its erroneously crediting the allocations to methods that call `HasLeadingCommentMatching` and have the method call inlined. It also thinks a vey small number of closure/func allocations are occuring after the changes???
> feat: convert Linq to code to prevent closure

- Src/CSharpier/DocPrinter/DocFitter.cs
- Src/CSharpier/DocPrinter/DocPrinter.cs
Instead of creating a new instance of `StringBuilder` and `Stack<PrintCommand>` every time `DocFitter.Fit` is called we instead create a single instance of each in `DocPrinter` and pass it into `DocFitter.Fit`.
This could be replaced by using `ValueStringBuilder` and `ValueListBuilder`, the latter would be beneficial as unlike `Stack<T>` we can access items by index instead of the `O(n)` lookup time with `ElementAt`.
| Method                | Mean     | Error   | StdDev  | Median   | Gen0       | Gen1      | Gen2      | Allocated |
|---------------------- |---------:|--------:|--------:|---------:|-----------:|----------:|----------:|----------:|
| Default_CodeFormatter | 231.5 ms | 4.62 ms | 8.78 ms | 228.0 ms | 11000.0000 | 4000.0000 | 1000.0000 |  95.82 MB |
| Method                | …
> feat: reuse collection types for `DocFitter`

- Src/CSharpier/SyntaxPrinter/Token.cs
- Use length check in `PrintTrailingTrivia` to return early, prevents `List<Doc>` allocation saving 1MB
- Pass `SyntaxTriviaList` by `in` because its a pretty large struct
> feat: add early return to `PrintTrailingTrivia`

- Src/CSharpier/Utilities/StackExtensions.cs
Overload for `ElementAt` to prevent boxing `Stack<T>.Enumerator`. Saves 0.9MB
| Method                | Mean     | Error   | StdDev  | Gen0       | Gen1      | Gen2      | Allocated |
|---------------------- |---------:|--------:|--------:|-----------:|----------:|----------:|----------:|
| Default_CodeFormatter | 234.0 ms | 4.50 ms | 5.85 ms | 11000.0000 | 4000.0000 | 1000.0000 |  95.82 MB |
| Method                | Mean     | Error   | StdDev  | Gen0       | Gen1      | Gen2      | Allocated |
|---------------------- |---------:|--------:|--------:|-----------:|----------:|----------:|----------:|
| Default_CodeFormatter | 233.0 ms | 4.63 ms | 7.35 ms | 11000.0000 | 4000.0000 | 1000.0000 |  94.96 MB |
> feat: add `Stack.ElementAt` overload, prevents Enumerator allocation

- Src/CSharpier/DocTypes/Align.cs
- Src/CSharpier/DocTypes/AlwaysFits.cs
- Src/CSharpier/DocTypes/BreakParent.cs
- Src/CSharpier/DocTypes/Concat.cs
- Src/CSharpier/DocTypes/ConditionalGroup.cs
- Src/CSharpier/DocTypes/ForceFlat.cs
- Src/CSharpier/DocTypes/HardLineNoTrim.cs
- Src/CSharpier/DocTypes/IfBreak.cs
- Src/CSharpier/DocTypes/IndentDoc.cs
- Src/CSharpier/DocTypes/LeadingComment.cs
- Src/CSharpier/DocTypes/LiteralLine.cs
- Src/CSharpier/DocTypes/NullDoc.cs
- Src/CSharpier/DocTypes/Region.cs
- Src/CSharpier/DocTypes/StringDoc.cs
- Src/CSharpier/DocTypes/TrailingComment.cs
- Src/CSharpier/DocTypes/Trim.cs
Csharpier spends 7% of the time calling `IsInstanceOfClass` (IIRC think this is what `is` is lowered into). By sealing `Doc` types csharp should be able to do faster type comparison.
> feat: add `sealed` to `Doc` objects

- Src/CSharpier/SyntaxPrinter/Token.cs
Use length check in PrintTrailingTrivia to return early, prevents List<Doc> allocation saving 1.9MB, 2%.
> feat: add early return to `PrivatePrintLeadingTrivia`

- Src/CSharpier.Cli.Tests/CliTests.cs
- Src/CSharpier.Cli/CommandLineFormatter.cs
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Cli/Server/CSharpierServiceImplementation.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
- docs/Ignore.md
Closes #631 
CSharpier now works as follows.
- .gitignore files are considered when determining if a file will be ignored. A .gitignore file at the same level as a given file will take priority over a .gitignore file above it in the directory tree.
- If a .csharpierignore file is present at the same level or anywhere above the given file in the tree and it contains a pattern for a given file, that will take priority.
- The patterns within .csharpierignore work the same as a .gitignore, with patterns lower in the file taking priority over patterns above
- CSharpier does not currently look further up the directory tree for additional .csharpierignore files if it finds one. But it does look for .gitignore files. If there is demand this could be added later.
> Modifying CSharpier to support reading gitignore files to determine what files are ignored.

- Src/CSharpier/SyntaxPrinter/SeparatedSyntaxList.cs
- Src/CSharpier/Utilities/ListExtensions.cs
Overload for `FirstOrDefault(this SyntaxTriviaList source`, stops `SyntaxTriviaList` being boxed saving 0.9MB
> feat: add `FirstOrDefault` overload

- Src/CSharpier/SyntaxPrinter/RightHandSide.cs
Prevent unnecessary `Guid.ToString()` allocation using interpolated string. Saves 0.3MB
| Default_CodeFormatter | 234.9 ms | 11.21 ms | 33.05 ms | 7000.0000 | 3000.0000 | 1000.0000 |  66.17 MB |
| Default_CodeFormatter | 230.9 ms | 9.77 ms | 28.66 ms | 220.6 ms | 7000.0000 | 3000.0000 | 1000.0000 |  65.86 MB |
> feat: use interpolated string in `RightHandSide`

- Src/CSharpier/DocPrinter/DocPrinter.cs
Converts `PrintCommand` to a struct, this is a massive memory and performance improvement 😄 
Converting types to a struct sometimes causes regressions from copying so I had held of on this one.
| Method                | Mean     | Error   | StdDev   | Gen0      | Gen1      | Gen2      | Allocated |
|---------------------- |---------:|--------:|---------:|----------:|----------:|----------:|----------:|
| Default_CodeFormatter | 206.3 ms | 4.11 ms | 10.00 ms | 7000.0000 | 3000.0000 | 1000.0000 |  66.17 MB |
| Method                | Mean     | Error   | StdDev  | Gen0      | Gen1      | Allocated |
|---------------------- |---------:|--------:|--------:|----------:|----------:|----------:|
| Default_CodeFormatter | 176.3 ms | 3.46 ms | 5.17 ms | 4000.0000 | 2000.0000 |  46.53 MB |
I did …
> feat: convert `PrintCommand` to value type

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/UncheckedStatements.test
Noticed that tests weren't failing for #1509 when I forgot to account for `SyntaxKind.UncheckedStatement`. This will hopefully catch it
> test: add test for unchecked statements/expressions

- Src/CSharpier/SyntaxPrinter/CSharpierIgnore.cs
- Src/CSharpier/Utilities/CharacterSizeCalculator.cs
- Add `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to `CalculateWidth`, I assumed the JIT would do this but perhaps not
- Use `SyntaxKind` in `IsNodeIgnored`
Benchmarks appear to show a suprising speedup, although I don't know if this is accurate.
| Method                | Mean    | Error    | StdDev   | Median  | Gen0       | Gen1       | Gen2       | Allocated |
|---------------------- |--------:|---------:|---------:|--------:|-----------:|-----------:|-----------:|----------:|
| Default_CodeFormatter | 1.637 s | 0.0329 s | 0.0969 s | 1.598 s | 52000.0000 | 31000.0000 | 10000.0000 | 420.54 MB |
| Method                | Mean    | Error    | StdDev   | Gen0       | Gen1       | Gen2      | Allocated |
|---------------------- …
> perf: inline hot path and remove `IsInstanceOf` usage

- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
- Remove unnecessary `ToList` call - 0.15 MB
- Extract a linq call and convert it to code - 0.8 MB
| Method                | Mean     | Error   | StdDev   | Gen0      | Gen1      | Allocated |
|---------------------- |---------:|--------:|---------:|----------:|----------:|----------:|
| Default_CodeFormatter | 191.4 ms | 4.05 ms | 11.81 ms | 4000.0000 | 2000.0000 |  42.24 MB |
| Method                | Mean     | Error    | StdDev   | Median   | Gen0      | Gen1      | Allocated |
|---------------------- |---------:|---------:|---------:|---------:|----------:|----------:|----------:|
| Default_CodeFormatter | 157.3 ms | 11.59 ms | 34.18 ms | 138.8 ms | 4000.0000 | 2000.0000 |  41.29 MB |
> perf: remove unnecessary `ToList` call and convert linq to code

- Src/CSharpier/Utilities/ListExtensions.cs
Add `Any` overload for `SyntaxTokenList`, saves 0.5 MB on the complex code bencmark. 
| Method                        | Mean     | Error   | StdDev   | Gen0      | Gen1      | Gen2      | Allocated |
|------------------------------ |---------:|--------:|---------:|----------:|----------:|----------:|----------:|
| Default_CodeFormatter_Complex | 241.7 ms | 7.22 ms | 21.17 ms | 7000.0000 | 4000.0000 | 1000.0000 |  61.61 MB |
| Method                        | Mean     | Error   | StdDev  | Gen0      | Gen1      | Gen2      | Allocated |
|------------------------------ |---------:|--------:|--------:|----------:|----------:|----------:|----------:|
| Default_CodeFormatter_Complex | 234.2 ms | 4.65 ms | 6.82 ms | 7000.0000 | 4000.0000 | 1000.0000 |  61.09 MB |
> perf: add `Any` overload for `SyntaxTokenList`

- Src/CSharpier/Utilities/ListExtensions.cs
Saves 0.09MB on the `CodeAxesTest` and 0.5MB on #1533
| Method                        | Mean     | Error   | StdDev  | Gen0      | Gen1      | Gen2      | Allocated |
|------------------------------ |---------:|--------:|--------:|----------:|----------:|----------:|----------:|
| Default_CodeFormatter_Complex | 228.4 ms | 4.55 ms | 6.53 ms | 7000.0000 | 4000.0000 | 1000.0000 |  61.62 MB 
| Method                        | Mean     | Error   | StdDev  | Gen0      | Gen1      | Gen2      | Allocated |
|------------------------------ |---------:|--------:|--------:|----------:|----------:|----------:|----------:|
| Default_CodeFormatter_Complex | 210.4 ms | 3.41 ms | 3.35 ms | 7000.0000 | 4000.0000 | 1000.0000 |  61.09 MB |
> perf: use `params ReadOnlySpan` for `List.Add`

- Src/CSharpier/SyntaxPrinter/ConstraintClauses.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseTypeDeclaration.cs
This is a nitpick PR, it probably saves 0.07 MB on the complex code benchmark
- convert `ConstraintClauses.Print`  to use `SyntaxList<TypeParameterConstraintClauseSyntax>` to prevent boxing
> perf: preventing boxing of `SyntaxList<ConstrainClause>`

- Src/CSharpier.Benchmarks/CodeSamples/Syntax.txt
- Src/CSharpier.Benchmarks/Program.cs
Add benchmark for complex object oriented code. This should give us more insight into the behaviour of non test code.
- Features several type declarations, inheritance
- Lots of comments and documentation
- Similar line count to `AxesTest` but takes twice as long
| Method                                  | Mean          | Error        | StdDev       | Gen0      | Gen1      | Gen2      | Allocated   |
|---------------------------------------- |--------------:|-------------:|-------------:|----------:|----------:|----------:|------------:|
| Default_CodeFormatter_Tests             | 103,058.08 us | 2,008.792 us | 3,067.637 us | 3500.0000 | 2000.0000 |  500.0000 |  34960.8 KB |
| Default_CodeFormatter_Complex           | 213,918.74 us | 3,716.222 us | 4,832.138 us | 7000.0000 | 4000.0000 | …
> bench: add complex code benchmark

- Src/CSharpier/SyntaxPrinter/Modifiers.cs
- Src/CSharpier/Utilities/ListExtensions.cs
- Use non boxing `ToArray` method.
- Use `Array.Sort` instead of `OrderBy` 
- This could be a mistake. `OrderBy` is a stable sort whereas `Array.Sort` is unstable. If I understand correctly, this won't be a problem as csharpier will never encounter a situation where `SyntaxTokenList` contains 2 modifiers with the same name (but potentially different trivia). I don't know if preprocessor directives could break this 
- Replace `Zip().Any()` with a custom `SequenceEquals` (this prevents boxing `SyntaxTokenList`)
- Remove unnecessary `ToArray` call
Saves 1 MB on Tests benchmark and 1.8 MB on the Complex benchmark. This is a lot more that I expected, dotmemory claims shows a 200KB reduction but the benchmarks think otherwise 🤔 
| Method                        | Mean     | Error   | StdDev   | …
> perf: optimise `Modifiers`, remove linq and array allocations

- Src/CSharpier.Generators/NodePrinterGenerator.cs
- Src/CSharpier.Generators/NodePrinterGenerator.sbntxt
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/LabeledStatements.test
- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchStatements.test
- Use `switch (syntaxNode.Kind())` instead of `is`. Should be slightly faster 🤞 
- Add `Debug.Assert` in the default branch to ensure that future changes to roslyn / mistakes with `SyntaxKind` are caught
Ran `FormatAsync` in a for loop 10 times to try and average performance. Seems to show a small 1.5% increase in performance at the cost of more complexity and the potential for errors. Do you think its worth merging this pr @belav ? TBH I'm a little dissapointed 😅 
I did wonder if using chained `or` might affect the generated code 🤷 the massive `SyntaxKind` switch statements in roslyn use several `case` tags instead. Perhaps this is lowered into better code? Looking at the IL I think it creates a jump table, although I'm not sure - I'm not fluent in IL 😄 .
| Method                | Mean …
> feat: convert `Node.Print` to use `switch (node.Kind())`

- Src/CSharpier.Cli/CommandLineFormatter.cs
- Use `Stopwatch.GetTimestamp` instead of `Stopwatch`
- Replace `Task.WaitAll` with the `async` `Task.WhenAll` - this should be a straight upgrade right? It has been a while since I read up on the difference
- Could Csharpier potentially use `Paralllel.ForeachAsync` here?
> perf: use `Stopwatch.GetTimestamp` and `Task.WhenAll`

- Src/CSharpier.Tests/FormattingTests/TestFiles/cs/SwitchExpressions.test
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InvocationExpression.cs
> Handle weird edge case with switch expression inside parenthesized expression followed by a long invocation chain

- Src/CSharpier/DocPrinter/DocPrinter.cs
- Src/CSharpier/Utilities/StringBuilderExtensions.cs
Prevents duplication of the result string, saving memory in certain cases, ie. a preprocessor directive at the start of a file.
| Method                        | Mean      | Error    | StdDev   | Gen0      | Gen1      | Allocated |
|------------------------------ |----------:|---------:|---------:|----------:|----------:|----------:|
| Default_CodeFormatter_Tests   |  98.32 ms | 1.954 ms | 2.327 ms | 2000.0000 | 1000.0000 |  31.07 MB |
| Default_CodeFormatter_Complex | 206.40 ms | 3.671 ms | 5.716 ms | 5000.0000 | 2000.0000 |  54.58 MB |
| Method                        | Mean      | Error    | StdDev   | Gen0      | Gen1      | Allocated |
|------------------------------ |----------:|---------:|---------:|----------:|----------:|----------:|
| Default_CodeFormatter_Tests   |  86.67 ms | …
> perf: add `TrimStart(this StringBuilder`

- Src/CSharpier/DocTypes/Doc.cs
- Src/CSharpier/SyntaxPrinter/AttributeLists.cs
- Src/CSharpier/SyntaxPrinter/SeparatedSyntaxList.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AnonymousMethodExpression.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AnonymousObjectMemberDeclarator.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Argument.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/AttributeList.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseFieldDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BasePropertyDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/DelegateDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/EnumMemberDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/ForStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/IfStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Interpolation.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/LabeledStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/NamespaceDeclaration.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/Parameter.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/QueryBody.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/RecursivePattern.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/SwitchSection.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/TryStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/UsingStatement.cs
- Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/VariableDeclarator.cs
- Src/CSharpier/SyntaxPrinter/Token.cs
Follow on from #1502, using `ValueListBuilder` to replace known `List<Doc>` sizes.
- Most of these changes aren't measurable in the benchmarks, many are insignificant, although I suspect this is partly due to the limited code found in the benchmark file.
- This PR will increase the performance benefits of #1524
@belav what do you think the best way of replacing a list that uses a collection initializer is?
I can either add the items directly into the scratch buffer and manually update `Length`
```C#
var docs = new ValueListBuilder<Doc>
([
Modifiers.Print(node.Modifiers, context),
Token.Print(node.DelegateKeyword, context),
null,null
]);
docs.Length = 2;
```
Or create the buffer and then append the items via params.
```C#
var docs = new ValueListBuilder<Doc>([null, null, null, null]); …
```
> perf: use `ValueListBuilder<T>` for constant buffers

- CHANGELOG.md
- Directory.Packages.props
- Src/CSharpier.Cli/CSharpier.Cli.csproj
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- docs/Ignore.md
Using gitignore parser library instead of building ignore rules ourselves improves csharpier performance drastically even with large repositories and a lot of ignore rules.
This would introduce a potentially breaking change as the rules are now case-sensitive by default since git is as well.
I had to remove one unit test as we would not parse the ignore-files ourselves anymore as well as alter one which was testing case-insensitive paths.
> Use alternative library to parse csharpier- and git-ignore files

- Src/CSharpier.Cli/EditorConfig/EditorConfigFileParser.cs
- Src/CSharpier.Cli/EditorConfig/EditorConfigLocator.cs
- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Cli/Options/OptionsProvider.cs
- Src/CSharpier.Core/SharedFunc.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
- Src/CSharpier.Tests/OptionsProviderTests.cs
- Src/CSharpier.Tests/SharedFuncTests.cs
Part of #1588, based on #1591 to help avoid any conflicts.
Initial POC shows that we don't redo the work anymore creating `IgnoreFile`, but there are some bugs to address.
> Changes to ensure we don't do the same work to create ignore files in two different threads.

- Src/CSharpier.Cli/IgnoreFile.cs
- Src/CSharpier.Tests/CommandLineFormatterTests.cs
> Only look for gitignore files inside the scope of the current git repo

- docs/Pre-commit.md
Running the suggested task-runner.json before would match no files, as husky .net does not support the {a,b} splitting pattern.
before:
after:
> docs: fix pre-commit task-runner.json

- Src/CSharpier.Core/CSharp/SyntaxPrinter/CSharpierIgnore.cs
- Src/CSharpier.Core/CSharp/SyntaxPrinter/MembersWithForcedLines.cs
- Src/CSharpier.Core/CSharp/SyntaxPrinter/SeparatedSyntaxList.cs
- Src/CSharpier.Core/CSharpier.Core.csproj
- Src/CSharpier.Core/Utilities/StringBuilderExtensions.cs
- Src/CSharpier.Core/Utilities/ValueListBuilder.cs
- Replaces `StringBuilder` with `ValueListBuilder<char>`
- Added some extension methods to make this easier
- Uses `SkipLocalsInit` to avoid the cost to zero `stackalloc char[]`
I have no idea why, all the new changes I make are slower in the benchmarks, even when they should be a straight upgrade 🤔 
I'm running into this issue a lot with #1542
| Method                        | Mean     | Error   | StdDev   | Median   | Gen0      | Gen1      | Allocated |
|------------------------------ |---------:|--------:|---------:|---------:|----------:|----------:|----------:|
| Default_CodeFormatter_Tests   | 133.7 ms | 2.65 ms |  3.54 ms | 133.7 ms | 2000.0000 | 1000.0000 |  31.07 MB |
| Default_CodeFormatter_Complex | 284.9 ms | 5.60 ms | 13.95 ms | 279.1 ms | 5000.0000 | 2000.0000 |  54.59 MB | …
> perf: replace `StringBuilder` with `ValueListBuilder<char>`

- docs/Pre-commit.md
The command for running the CSharpier tool is `dotnet tool run CSharpier format FILENAME`. `format` was missing in the sample hook configuration.
> docs: fix missing format command in pre-commit config

- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessProvider.java
- Fixed NullPointerException in `CSharpierProcessProvider.findVersionInCsProj()` method
- Added defensive null check for `File.listFiles()` return value
- Enhanced debug logging for directory access failures
The Rider plugin was crashing with NPE when Git filesystem operations made directories temporarily inaccessible, causing `File.listFiles()` to return null. The enhanced for loop would then throw NullPointerException when trying to iterate over the null array.
**Environment:** Linux Mint Debian Edition, CSharpier plugin 2.2.2, Rider 2025.2.1
**Stack trace from IDE Internal Errors dialog:**
```
java.lang.NullPointerException
at com.intellij.csharpier.CSharpierProcessProvider.findVersionInCsProj(CSharpierProcessProvider.java:207)
at …
```
> Fix NullPointerException in CSharpier Rider plugin when directories are inaccessible

- Src/CSharpier.Rider/src/main/java/com/intellij/csharpier/CSharpierProcessProvider.java
The CSharpier Rider plugin was throwing an IOException when trying to execute dotnet commands, preventing the plugin from detecting CSharpier versions and establishing formatting processes.
**Error Details:**
```
java.io.IOException: Cannot run program "/usr/share/dotnet/dotnet" (in directory "749bf0c6:/home/robert/code/recyclarr:/home/robert/code/recyclarr/src/Recyclarr.Core/TrashGuide"): error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
at com.intellij.csharpier.ProcessHelper.executeCommand(ProcessHelper.java:34)
at com.intellij.csharpier.DotNetProvider.execDotNet(DotNetProvider.java:111)
at com.intellij.csharpier.CSharpierProcessProvider.findCSharpierVersionInToolOutput(CSharpierProcessProvider.java:147)
```
**Environment:**
- OS: …
> Fix IOException: Cannot run program dotnet in Rider plugin

- Src/CSharpier.MsBuild/build/CSharpier.MsBuild.targets
Many of my test projects fail to build when `csharpier` is added to them. They fail with this message:
```
Build FAILED.
"/Users/danny/src/tdg5/csharpier-build-issue-reproduction/App.Tests.csproj" (Rebuild target) (1:7) ->
"/Users/danny/src/tdg5/csharpier-build-issue-reproduction/App.Tests.csproj" (CSharpierFormatInner target) (1:8) ->
/usr/local/share/dotnet/sdk/9.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(201,38):
error MSB4184: The expression "[MSBuild]::VersionLessThan('', 6.0)" cannot be
evaluated. Version string was not in a correct format.
[/Users/danny/src/tdg5/csharpier-build-issue-reproduction/App.Tests.csproj]
```
For some reason, I only run into this problem with my test projects that include `xunit.v3`, but I'm fairly certain this is …
> Fix condition causing FirstTargetFramework build property erasure
